-- QUERY CUENTAS QUE MÁS SE REPITEN
SELECT
  Conta.CUENTA_CONTABLE,
  Cuenta.NOMBRE,
  Conta.CENTRO_DE_COSTO,
  CentroCosto.DESCRIPCION,
  Proveedor.N_I_T,
  Proveedor.NOMBRE_COMPLETO
FROM
  CGO_CXP AS Cargo
  LEFT JOIN EMPRESA AS Empresa ON Cargo.EMPRESA = Empresa.NUMERO
  LEFT JOIN CONTCCXP AS Conta ON Cargo.NUMERO_INTERNO = Conta.NUMERO_CGO_CXP
  LEFT JOIN PRVEEDOR AS Proveedor ON Cargo.PROVEEDOR = Proveedor.NUMERO
  LEFT JOIN CUENTA AS Cuenta ON Conta.CUENTA_CONTABLE = Cuenta.CLAVE
  LEFT JOIN CTROCSTO AS CentroCosto ON Conta.CENTRO_DE_COSTO = CentroCosto.NUMERO
WHERE
  Empresa.CLAVE = 'PERFILES'
  AND Cuenta.EMPRESA = 'PERFILES'
  AND Conta.VALOR_CARGO <> 0
  AND TRIM(REPLACE(Proveedor.N_I_T, '-', '')) = '105181137' 
  
-- QUERY CUENTA QUE MÁS SE REPITE, DELIMITADO POR LA PRIMERA QUE APARECE
SELECT
  TOP 1 TRIM(Conta.CUENTA_CONTABLE) AS CUENTA_CONTABLE,
  COUNT(Conta.CUENTA_CONTABLE) as NumRepeticiones,
  TRIM(Cuenta.NOMBRE) AS NOMBRE_CUENTA_SUGERIDA,
  CONVERT(VARCHAR(50), Conta.CENTRO_DE_COSTO) AS CENTRO_DE_COSTO,
  TRIM(CentroCosto.DESCRIPCION) AS DESCRIPCION_CENTRO_DE_COSTO,
  TRIM(Proveedor.N_I_T) AS NIT_PROVEEDOR,
  TRIM(Proveedor.NOMBRE_COMPLETO) AS NOMBRE_PROVEEDOR
FROM
  CGO_CXP AS Cargo
  LEFT JOIN EMPRESA AS Empresa ON Cargo.EMPRESA = Empresa.NUMERO
  LEFT JOIN CONTCCXP AS Conta ON Cargo.NUMERO_INTERNO = Conta.NUMERO_CGO_CXP
  LEFT JOIN PRVEEDOR AS Proveedor ON Cargo.PROVEEDOR = Proveedor.NUMERO
  LEFT JOIN CUENTA AS Cuenta ON Conta.CUENTA_CONTABLE = Cuenta.CLAVE
  LEFT JOIN CTROCSTO AS CentroCosto ON Conta.CENTRO_DE_COSTO = CentroCosto.NUMERO
WHERE
  Empresa.CLAVE = 'PERFILES'
  AND Cuenta.EMPRESA = 'PERFILES'
  AND Conta.CUENTA_CONTABLE <> '170505001'
  AND Conta.VALOR_CARGO <> 0
  AND TRIM(REPLACE(Proveedor.N_I_T, '-', '')) = '74485067'
GROUP BY
  Conta.CUENTA_CONTABLE,
  Cuenta.NOMBRE,
  Conta.CENTRO_DE_COSTO,
  CentroCosto.DESCRIPCION,
  TRIM(Proveedor.N_I_T),
  Proveedor.NOMBRE_COMPLETO
HAVING
  COUNT(Conta.CUENTA_CONTABLE) = (
    SELECT
      MAX(CuentaContableCount) as MaxCount
    FROM
      (
        SELECT
          COUNT(Conta.CUENTA_CONTABLE) as CuentaContableCount
        FROM
          CGO_CXP AS Cargo
          LEFT JOIN EMPRESA AS Empresa ON Cargo.EMPRESA = Empresa.NUMERO
          LEFT JOIN CONTCCXP AS Conta ON Cargo.NUMERO_INTERNO = Conta.NUMERO_CGO_CXP
          LEFT JOIN PRVEEDOR AS Proveedor ON Cargo.PROVEEDOR = Proveedor.NUMERO
          LEFT JOIN CUENTA AS Cuenta ON Conta.CUENTA_CONTABLE = Cuenta.CLAVE
          LEFT JOIN CTROCSTO AS CentroCosto ON Conta.CENTRO_DE_COSTO = CentroCosto.NUMERO
        WHERE
          Empresa.CLAVE = 'PERFILES'
          AND Cuenta.EMPRESA = 'PERFILES'
          AND Conta.CUENTA_CONTABLE <> '170505001'
          AND Conta.VALOR_CARGO <> 0
          AND TRIM(REPLACE(Proveedor.N_I_T, '-', '')) = '74485067'
        GROUP BY
          Conta.CUENTA_CONTABLE
      ) as CuentaContableCounts
  )