SELECT
  TRIM(Conta.CUENTA_CONTABLE) AS CUENTA_CONTABLE,
  COUNT(Conta.CUENTA_CONTABLE) as NumRepeticiones,
  TRIM(Cuenta.NOMBRE) AS NOMBRE_CUENTA_SUGERIDA,
  CONVERT(VARCHAR(50), Conta.CENTRO_DE_COSTO) AS CENTRO_DE_COSTO,
  TRIM(CentroCosto.DESCRIPCION) AS DESCRIPCION_CENTRO_DE_COSTO,
  TRIM(Proveedor.N_I_T) AS NIT_PROVEEDOR,
  TRIM(Proveedor.NOMBRE_COMPLETO) AS NOMBRE_PROVEEDOR,
  CONVERT(VARCHAR(50), Proveedor.NUMERO) AS CODIGO_PROVEEDOR,
  Cargo.TIPO_CGO_CXP AS TIPO
FROM
  CGO_CXP AS Cargo
  LEFT JOIN EMPRESA AS Empresa ON Cargo.EMPRESA = Empresa.NUMERO
  LEFT JOIN CONTCCXP AS Conta ON Cargo.NUMERO_INTERNO = Conta.NUMERO_CGO_CXP
  LEFT JOIN PRVEEDOR AS Proveedor ON Cargo.PROVEEDOR = Proveedor.NUMERO
  LEFT JOIN CUENTA AS Cuenta ON Conta.CUENTA_CONTABLE = Cuenta.CLAVE
  LEFT JOIN CTROCSTO AS CentroCosto ON Conta.CENTRO_DE_COSTO = CentroCosto.NUMERO
WHERE
  Empresa.CLAVE = 'PERFILES'
  AND Cuenta.EMPRESA = 'PERFILES'
  AND Conta.VALOR_CARGO <> 0
  AND TRIM(REPLACE(Proveedor.N_I_T, '-', '')) = '42818575'
  AND (
    Conta.CUENTA_CONTABLE NOT IN ('170505001', '130505001', '220505001', '1141')
  )
  AND (
    Cargo.TIPO_CGO_CXP IN ('FC', 'PQ', 'CC', 'FI', 'PA')
  )
GROUP BY
  Conta.CUENTA_CONTABLE,
  Cuenta.NOMBRE,
  Conta.CENTRO_DE_COSTO,
  CentroCosto.DESCRIPCION,
  TRIM(Proveedor.N_I_T),
  Proveedor.NOMBRE_COMPLETO,
  Proveedor.NUMERO,
  Cargo.TIPO_CGO_CXP
ORDER BY
  (Conta.CUENTA_CONTABLE) DESC,
  CUENTA_CONTABLE